### PR TITLE
Simple change to implement Default on map

### PR DESCRIPTION
**Pull request by mjkoo**
Default trait is implemented for RawMap but not on Map, add an implementation that creates an empty map as in RawMap.

### CODE REVIEW

**Comment by chris-morgan** [comment]
I can’t imagine why RawMap implements Default and Map doesn’t.

Given the implementation of Default for RawMap, mightn’t it just as well be put in the impl_common_methods macro? It seems to work.

**Comment by mjkoo** [comment]
Think that makes sense to me, is this what you meant?

**Comment by chris-morgan** [comment]
Thanks for that. I put it in with a handful of commits I had made locally but apparently not pushed.

I must make a release.

**Comment by vi** [comment]
When on crates.io?

**Pull request closed without merging**
