### PR TITLE
Implement stuff for concurrency.

### LINKED ISSUE #19: concurrent feature
Just for the record, since we already discussed this a bit.

It would be nice if we created a `concurrent` feature that would basically add the `Sync + Send` bounds where necessary. I already do something similar in my [minor fork](https://github.com/blaenk/anymap/compare/master...blaenk:clone) and found that it's a very straightforward change compared to making it clonable.

Personally I really need this so that I could put stuff in an `Arc` and send it to a thread pool, but I understand if it's more of a hassle than it's worth here.

Specifically I need it to be both clonable _and_ concurrent. What I was discussing on IRC was that I don't know if it'd be possible to have to independent _yet composable_ features for each thing: `clone` and `concurrent`, given the fact (?) that the `with_clone` stuff would need to have the `Sync + Send` bounds added.

### PR DESCRIPTION
**Pull request by chris-morgan**
This took some refactoring too for best effect.

Fixes #19.

### CODE REVIEW

**Comment by blaenk** [comment]
YESS!! :)

**Comment by blaenk** [comment]
I think this is a good compromise implementation. You managed to do very little repeating thanks to that macro, much better than the worst-case scenario naive/brute-force implementation I was afraid of.

Thanks a ton for this. I had been running my own fork for a while. I'm sure it'll be useful to others too.

**Comment by reem** [comment]
An alternative approach from typemap: https://github.com/reem/rust-typemap/compare/d6b191938cc951736410c5eccb5af90b5d8c4422...master

**Comment by chris-morgan** [comment]
I’ve gone ahead and used the approach of arcane DST magicks. There were some hiccups with it but  I believe I’ve got it working satisfactorily.

**Comment by blaenk** [comment]
so are we gonna do this?

**Comment by Ogeon** [comment]
I'm also very interested in this feature, since I would like to use it in Rustful. How are things going?

**Comment by chris-morgan** [comment]
This has landed in anymap v0.11.0. Sorry I forgot to merge it.

**Comment by Ogeon** [comment]
Wooh! :tada:

**Pull request closed without merging**
